version: '3.8' 

services:
  db: 
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gorgun
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    volumes:
      - /WorkSpace/Projetos/Projeto_MongoDB/bddata:/data/db

